name: Run Cypress Tests
on: [push]
jobs: 
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          build: npm run build
          start: npm start